kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-bot-config
  namespace: {{ .Release.Namespace }}
data:
  script.sh: |
    #!/bin/sh
    temp_folder=$(mktemp -d)

    python /bot/loadKeys.py /bot/internal/interface.json $temp_folder

    certPinning="{{ .Values.certificates.certPinning}}"
    
    if [ -n "$certPinning" ] && [ "$certPinning" = "true" ]; then
      ./bot/fingerprints.sh $temp_folder/TLS {{ .Release.Name }} $pattern
      python /bot/updateFingerprints.py $temp_folder/TLS/nginx_conf
    else 
      echo "Source Folder and/or certFilePattern empty. Skip the fingerprint pinning"
    fi 

    python /bot/updateCaBundle.py $temp_folder/CA 
    python /bot/annotateIngress.py

    rm -rf $temp_folder