kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ .Release.Name }}-bot
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template: 
        spec:
          serviceAccountName: {{ .Release.Name }}-service-account
          volumes:
            - name: {{ .Release.Name }}-bot-config
              configMap:
                name: {{ .Release.Name }}-bot-config
                defaultMode: 420
          containers:
            - name: {{ .Release.Name }}-bot
              image: {{ .Values.image}}
              env:  
                - name: RELEASE_NAME
                  value: {{ .Release.Name }}
                - name: CONFIG_TAG
                  value: {{ .Values.config.tag }}
                - name: CONFIG_MAP
                  value: {{ .Values.config.map }}      
                - name: CONFIG_REPO
                  value: {{ .Values.config.repo }}
                - name: CERTIFICATES_SECRET
                  value: {{ .Release.Name }}-{{ .Values.certificates.secret }}
                - name: CONFIG_CONFIGLOADER
                  value: "{{ .Values.config.configLoader | join "," }}"
                - name: CONFIG_PUBKEYLOADER
                  value: "{{ .Values.config.pubKeyLoader | join "," }}"  
                {{- if .Values.pubKeyLoader.x509 }} 
                - name: X509_REPO
                  value: {{ .Values.pubKeyLoader.x509.repo }}
                - name: X509_CERTFILEPATTERN
                  value: {{ .Values.pubKeyLoader.x509.certFilePattern }}
                - name: X509_CAFILEPATTERN
                  value: {{ .Values.pubKeyLoader.x509.caFilePattern }}
                - name: X509_SOURCEFOLDER
                  value: {{ .Values.certificates.sourceFolder }}
                {{ end }} 
                {{- if .Values.pubKeyLoader.did }} 
                - name: DID_DOC_RESOLVER_URL
                  value: {{ .Values.pubKeyLoader.did.resolverUrl }}
                - name: DID_DOC_DIDS
                  value: "{{ .Values.pubKeyLoader.didDoc.dids| join "," }}"
                - name: DID_DOC_VER_TLS_FILTER
                  value: "{{ .Values.pubKeyLoader.didDoc.verificationMethods.tlsFilter| join ","  }}"
                - name: DID_DOC_VER_CA_FILTER
                  value: "{{ .Values.pubKeyLoader.didDoc.verificationMethods.caFilter| join ","  }}"
                {{ end }} 
                - name: CONTROLLER_CONFIG_MAP
                  value: {{ .Values.controller.config.map }}
                - name: CONTROLLER_CONFIG_NAMESPACE
                  value: {{ .Values.controller.namespace }}
                - name: INGRESS_NAME
                  value: {{ .Values.ingress.name }}
                - name: INGRESS_NAMESPACE
                  value: {{ .Release.Namespace}}
                - name: INGRESS_NAMESPACE
                  value: {{ .Release.Namespace}}
              args:
                - /bin/sh
                - /tmp/bot/script.sh
              resources: {}
              volumeMounts:
                - name: {{ .Release.Name }}-bot-config
                  mountPath: /tmp/bot
              imagePullPolicy: Always
          restartPolicy: Never
