kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ .Release.Name }}-bot
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template: 
        spec:
          serviceAccountName: {{ .Release.Name }}-service-account
          volumes:
            - name: {{ .Release.Name }}-bot-config
              configMap:
                name: {{ .Release.Name }}-bot-config
                defaultMode: 420
          containers:
            - name: {{ .Release.Name }}-bot
              image: alpine:3.18
              env: 
                - name: RELEASE_NAME
                  value: {{ .Release.Name }}
                - name: TAG
                  value: {{ .Values.config.tag }}
                - name: REPO
                  value: {{ .Values.config.repo }}
                - name: CERTIFICATES_REPO
                  value: {{ .Values.certificates.repo }}
                - name: CONTROLLER_CONFIG_MAP
                  value: {{ .Values.controller.config.map }}
                - name: CONTROLLER_CONFIG_NAMESPACE
                  value: {{ .Values.controller.namespace }}
                - name: CERTIFICATES_SECRET
                  value: {{ .Values.certificates.secret }}
                - name: INGRESS_NAME
                  value: {{ .Values.ingress.name }}
                - name: INGRESS_NAMESPACE
                  value: {{ .Values.ingress.namespace }}
              args:
                - /bin/sh
                - /tmp/script.sh
              resources: {}
              volumeMounts:
                - name: {{ .Release.Name }}-bot-config
                  mountPath: /tmp
              imagePullPolicy: Always
          restartPolicy: Never
