apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-ingress-rule-role
rules:
  - apiGroups:
      [
        "",
        "apps",
        "rbac.authorization.k8s.io",
        "roles.rbac.authorization.k8s.io",
        "authorization.k8s.io",
      ]
    resources: ["ingress"]
    verbs: ["get", "watch", "list", "create", "delete", "patch"]
