kind: ConfigMap
apiVersion: v1
metadata:
  name: whitelisting-bot-config
  namespace: default
data:
  script.sh: |
    #!/bin/sh
    apk add --update py-pip	
    git clone $REPO /repo
    pip install /repo/requirements.txt
    python /repo/updateFingerprints.py
    python /repoupdateCaBundle.py
