kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-bot-delete-hook-config
  namespace: {{ .Release.Namespace }}
annotations:
  "helm.sh/hook": pre-delete
  "helm.sh/hook-weight": "-4"
data:
  script.sh: |
    #!/bin/sh
    apk add --update py-pip	> /dev/null
    apk add --update git > /dev/null
    apk add --update bash > /dev/null
    git clone $REPO --branch $TAG bot
    pip install -r /bot/requirements.txt > /dev/null
    python /bot/removeFingerprints.py 
    python /bot/removeCaBundle.py 
    python /bot/removeIngressAnnotation.py
