kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-bot-config
  namespace: {{ .Release.Namespace }}
annotations:
  "helm.sh/hook": pre-delete
  "helm.sh/hook-weight": "-4"
data:
  script.sh: |
    #!/bin/sh
    apk add --update py-pip	> /dev/null
    apk add --update git > /dev/null
    apk add --update bash > /dev/null
    apk add --update openssl > /dev/null
    git clone $REPO --branch $TAG bot
    git clone $CERTIFICATEFOLDER certificateFolder 
    pip install -r /bot/requirements.txt > /dev/null
    ./bot/fingerprints.sh ./../certificateFolder
    python /bot/updateFingerprints.py ./../certificateFolder/nginx_conf
    python /bot/updateCaBundle.py /certificateFolder
    python /bot/annotateIngress.py
