kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role-binding
  namespace: {{ .Values.ingress.namespace}}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-ingress-rule-service-account
    namespace: {{ .Values.ingress.namespace}}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-ingress-rule-role
  apiGroup: rbac.authorization.k8s.io
