image: ghcr.io/schulzesttsi/nginx-ingress-whitelister:dev
ontroller:
  config:
    map: addon-http-application-routing-nginx-configuration
  namespace: ingress-nginx
config:
  map:
  configLoader:
    - internal.configLoader.ConfigMapLoader.ConfigMapLoader
    - internal.configLoader.EnvMapLoader.EnvMapLoader
  pubKeyLoader:
    - internal.pubKeyLoader.didLoader.didLoader
    - internal.pubKeyLoader.gitLoader.gitLoader
certificates:
  secret: gateway-ca-bundle
  certPinning: "true"
pubKeyLoader:
 x509:
  repo: Location for Folder
  sourceFolder: TLS
  certFilePattern: TLS*.pem
  caFilePattern: CA*.pem
 didDoc:
  resolverUrl: http://localhost:8080/1.0/identifiers/
  dids: 
  verificationMethods:
    tlsFilter: 
    caFilter:
ingress:
  name: gateway
job: 
  schedule: '*/1 * * * *'
universal-resolver:
  service:
    port: 8081
