controller:
  config:
    map: addon-http-application-routing-nginx-configuration
  namespace: ingress-nginx
config:
  repo: https://github.dev/WorldHealthOrganization/nginx-ingress-whitelister
  tag: main
  map:
  configLoader:
    - internal.configLoader.ConfigMapLoader.ConfigMapLoader
    - internal.configLoader.EnvMapLoader.EnvMapLoader
  pubKeyLoader:
    - internal.pubKeyLoader.didLoader.didLoader
    - internal.pubKeyLoader.x509Loader.x509Loader
certificates:
  secret: gateway-ca-bundle
  certPinning: "true"
pubKeyLoader:
 x509:
  repo: Location for Folder
  sourceFolder: TLS
  certFilePattern: TLS*.pem
  caFilePattern: CA*.pem
 didDoc:
  resolverUrl: http://localhost:8080/1.0/identifiers/
  dids: 
  verificationMethods:
    tlsFilter: 
    caFilter:
ingress:
  name: gateway
job: 
  schedule: '*/1 * * * *'